name: Gh-Pages

on:
  push:
    branches: [ master, bloc_handling ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
      - uses: bluefireteam/flutter-gh-pages@v7
