name: Gh-Pages

on:
  push:
    branches: [ master, bloc_handling ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          customArgs: --renderer=auto --base-href /
      - uses: bluefireteam/flutter-gh-pages@v7
